package zw.powertel.contracts.enums;

public enum ApprovalStatus {
    PENDING,
    LEGAL_APPROVED,
    LEGAL_REJECTED,
    TECHNICAL_APPROVED,
    TECHNICAL_REJECTED,
    FINANCIAL_APPROVED,
    FINANCIAL_REJECTED,
    COMMERCIAL_APPROVED,
    COMMERCIAL_REJECTED,
    BUSINESS_DEVELOPMENT_APPROVED,
    BUSINESS_DEVELOPMENT_REJECTED,
    PROCUREMENT_APPROVED,
    PROCUREMENT_REJECTED
}
