package zw.powertel.contracts.enums;

public enum RequisitionStatus {
    SUBMITTED,
    PALEGAL_APPROVED,
    PALEGAL_REJECTED,
    COMPANYSECRETARY_APPROVED,
    COMPANYSECRETARY_REJECTED,
    PROCUREMENTMANAGER_APPROVED,
    PROCUREMENTMANAGER_REJECTED,
    FINANCEDIRECTOR_APPROVED,
    FINANCEDIRECTOR_REJECTED,
    CONTRACT
    }

